# Generated by Django 5.1.3 on 2024-11-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('belt_level', models.CharField(choices=[('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('brown', 'Brown'), ('black', 'Black')], max_length=10)),
                ('karate_style', models.CharField(choices=[('shotokan', 'Shotokan'), ('goju_ryu', 'Goju-Ryu'), ('shito_ryu', 'Shito-Ryu'), ('kyokushin', 'Kyokushin'), ('wado_ryu', 'Wado-Ryu'), ('enshin', 'Enshin')], max_length=20)),
                ('club', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Athlete',
                'verbose_name_plural': 'Athletes',
            },
        ),
    ]
