# Generated by Django 5.1.3 on 2024-11-13 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurniejKarate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CHAMPIONSHIP', 'Championship'), ('REGIONAL', 'Regional'), ('CLUB', 'Club Tournament')], default='CLUB', max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('athlete1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_athlete1', to='TurniejKarate.athlete')),
                ('athlete2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_athlete2', to='TurniejKarate.athlete')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_won', to='TurniejKarate.athlete')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='TurniejKarate.tournament')),
            ],
        ),
    ]
