# Generated by Django 5.1.3 on 2024-11-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurniejKarate', '0002_tournament_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='athletes', to='TurniejKarate.tournament'),
        ),
    ]
