# Generated by Django 5.1.3 on 2024-11-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TurniejKarate', '0004_weightcategory_athlete_weight_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='tournaments',
        ),
    ]
