# Generated by Django 5.1.3 on 2024-11-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurniejKarate', '0005_remove_athlete_tournaments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={},
        ),
        migrations.AlterField(
            model_name='weightcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
