# Generated by Django 5.1.3 on 2024-11-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurniejKarate', '0007_tournament_athletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='place',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
